/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacupRouteImport } from './routes/teacup'
import { Route as MallardRouteImport } from './routes/mallard'
import { Route as GlizzyRouteImport } from './routes/glizzy'
import { Route as IndexRouteImport } from './routes/index'

const TeacupRoute = TeacupRouteImport.update({
  id: '/teacup',
  path: '/teacup',
  getParentRoute: () => rootRouteImport,
} as any)
const MallardRoute = MallardRouteImport.update({
  id: '/mallard',
  path: '/mallard',
  getParentRoute: () => rootRouteImport,
} as any)
const GlizzyRoute = GlizzyRouteImport.update({
  id: '/glizzy',
  path: '/glizzy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glizzy': typeof GlizzyRoute
  '/mallard': typeof MallardRoute
  '/teacup': typeof TeacupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glizzy': typeof GlizzyRoute
  '/mallard': typeof MallardRoute
  '/teacup': typeof TeacupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glizzy': typeof GlizzyRoute
  '/mallard': typeof MallardRoute
  '/teacup': typeof TeacupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/glizzy' | '/mallard' | '/teacup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/glizzy' | '/mallard' | '/teacup'
  id: '__root__' | '/' | '/glizzy' | '/mallard' | '/teacup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlizzyRoute: typeof GlizzyRoute
  MallardRoute: typeof MallardRoute
  TeacupRoute: typeof TeacupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacup': {
      id: '/teacup'
      path: '/teacup'
      fullPath: '/teacup'
      preLoaderRoute: typeof TeacupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mallard': {
      id: '/mallard'
      path: '/mallard'
      fullPath: '/mallard'
      preLoaderRoute: typeof MallardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glizzy': {
      id: '/glizzy'
      path: '/glizzy'
      fullPath: '/glizzy'
      preLoaderRoute: typeof GlizzyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlizzyRoute: GlizzyRoute,
  MallardRoute: MallardRoute,
  TeacupRoute: TeacupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
